### PR TITLE
PHPUnit 9 and PHP 8 support

### PR DESCRIPTION
**Pull request by chasepeeler**
This SHOULD allow this to work with PHPUnit 9 and PHP 8.

For PHP 8, I just needed to update a method signature to take in a parameter. I also removed a default value on a parameter that came before a parameter without a default value to get rid of the warning that it generated.

For PHPUnit 9, ResultPrinter was changed to an interface, and the previous ResultPrinter class was renamed to DefaultResultPrinter. So, what I did was update it to extend from DefaultResultPrinter. I then put a check in place that if the PHPUnit version was less than 9, it would create an alias from ResultPrinter to DefaultResultPrinter. 

composer test passed for both PHPUnit 8 and 9 against PHP 8. I can't easily switch back to PHP 7 to test it, but the two updates I made in relation to PHP itself shouldn't cause any issues with PHP 7.

### CODE REVIEW

**Comment by chasepeeler** [comment]
Ugh, the update I made to the printHeader method signature fails against PHPUnit 7. I'll See what I can do to fix that. 

Everything looked good against PHPUnit 8 and 9, except for the fact there was a segfault with PHP 7.2 - wonder what that's about?

**Comment by JeroenDeDauw** [comment]
We can drop support for older PHP/PHPUnit versions if that makes things easier.

**Comment by chasepeeler** [comment]
So, the issue is that PHPUnit 8+ has "protected function printHeader(TestResult $result): void" but PHPUnit 7 has "protected function printHeader(): void"

You'll throw an Error in PHP 8 if the signatures don't match, so you have to add that parameter to support PHP 8 and PHPUnit 8+. There is an exception though - you can add a default value to the parameter without causing any issues. So, you can make it "protected function printHeader(TestResult $result = null): void" and PHP 8 will be happy. If you fall back to PHPUnit 7 (which will force falling back to PHP 7), you'll be fine. Even if you didn't have to fallback to PHP 7, you'd still be fine, because it appears you can ADD parameters to a child method without issue - you just cant remove or change that were defined by the parent.

I pushed up that change. You can still drop support for PHPUnit 7 if you want, but it should work OK if you leave it.

The following configurations tested successfully on my machine (windows):
PHP 7.3.x and PHPUnit 7.x
PHP 7.3.x and PHPUnit 8.x
PHP 7.3.x and PHPUnit 9.x
PHP 8.0.x and PHPUnit 8.x
PHP 8.0.x and PHPUnit 9.x

**Comment by JeroenDeDauw** [comment]
Could also switch from TravisCI to GitHub Actions

**Comment by chasepeeler** [comment]
Well, 7.1-7.4 all passed this time, but 8.0 still had a segfault. I wonder if the escape sequences for the colors are causing it?

It's your project, so it's up to you if you want to switch to GitHub Actions.

**Comment by JeroenDeDauw** [comment]
Segfault also happening with other PHP: https://travis-ci.org/github/JeroenDeDauw/nyancat-phpunit-resultprinter/builds/758696934

What I was saying is that I'm fine with a change to the CI - might be easier to get things to work on GitHub than on Travis. Same goes for dropping support for older PHP and PHPUnit.

**Comment by chasepeeler** [comment]
Yea, the segfault happened with 7.3-8.0 using Xenial. It only happened with 8.0 using Xenial. With trusty it was happening on just 7.3. I don't know what is involved with switching to GitHub Actions - so, if you want switch, go for it. Like I said, it's your project.

As for dropping older versions of PHPUnit and PHP - again, it won't hurt to drop support for EOL versions, but at this point I don't think it's necessary. The segfault issue is happening on the newer PHP versions, and there aren't any issues with PHPUnit 7 or 8 either. So, feel free to drop support - but it isn't necessary in order to support PHPUnit 9 or PHP 8.

Let me know what else I can do.

**Comment by chasepeeler** [comment]
Okay, this should support github actions now. Configuration is in php.yml. It will run against PHP 7.1 - 8.0. 

PHP 7.1 will use PHPUnit 7.5
PHP 7.2 will use PHPUnit 8.5
PHP 7.3+ will use PHPUnit 9.5

All 5 jobs are passing for me.

**Comment by JeroenDeDauw** [comment]
Thanks a bunch! New version tagged

**Pull request merged**
